import logging
from typing import Optional, List, Dict, Any, Union
from pathlib import Path

from langgraph.graph import StateGraph, END
from langgraph.checkpoint.memory import MemorySaver

from agents.state.wizard_state import WizardAgentState, create_initial_state
from agents.nodes.supervisor import supervisor_node
from agents.nodes.rule_analyzer import rule_analyzer_node
from agents.nodes.cypher_generator import cypher_generator_node
from agents.nodes.validator import validator_node
from agents.nodes.data_dictionary import data_dictionary_node
from agents.nodes.reference_data import reference_data_node
from agents.nodes.rule_tester import rule_tester_node
from agents.audit.event_store import get_event_store
from agents.audit.event_types import AuditEventType

logger = logging.getLogger(__name__)


def human_review_node(state: WizardAgentState) -> WizardAgentState:
    """Human review node - workflow pauses here for human input."""
    state["requires_human_input"] = True
    state["events"].append({
        "event_type": "human_review_required",
        "agent_name": "human_review",
        "message": "Awaiting human review and input",
    })
    return state


def review_proposal_node(state: WizardAgentState) -> WizardAgentState:
    """Synthesize all agent outputs into a final policy proposal."""
    rule_def = state.get("rule_definition") or {}
    cypher = state.get("cypher_queries") or {}
    
    # Construct a visualization-friendly proposal
    state["proposal"] = {
        "rule_definition": rule_def,
        "cypher_queries": cypher,
        "summary": rule_def.get("description", "Policy draft generated by agents"),
        "confidence_score": 0.9 if state.get("success") else 0.6
    }
    
    state["events"].append({
        "event_type": "proposal_generated",
        "agent_name": "system",
        "message": "Policy proposal synthesized and ready for review",
    })
    
    return state


def complete_node(state: WizardAgentState) -> WizardAgentState:
    """Finalize successful workflow."""
    state["success"] = True
    state["events"].append({
        "event_type": "workflow_complete",
        "agent_name": "system",
        "message": "Workflow completed successfully",
    })

    event_store = get_event_store()
    session_id = state.get("origin_country", "unknown")
    event_store.append(
        session_id=session_id,
        event_type=AuditEventType.WORKFLOW_COMPLETED,
        data={
            "rule_id": state.get("rule_definition", {}).get("rule_id"),
            "iterations": state.get("iteration", 0),
        },
    )
    logger.info("Rule ingestion workflow completed successfully")
    return state


def fail_node(state: WizardAgentState) -> WizardAgentState:
    """Handle workflow failure. Cleans up any stale temp graphs."""
    state["success"] = False
    if not state.get("error_message"):
        state["error_message"] = "Workflow failed after max iterations"
    state["events"].append({
        "event_type": "workflow_failed",
        "agent_name": "system",
        "message": state.get("error_message", "Unknown error"),
    })

    # Cleanup stale temp graphs
    try:
        from services.database import get_db_service
        db = get_db_service()
        db.cleanup_stale_temp_graphs()
    except Exception:
        pass

    event_store = get_event_store()
    session_id = state.get("origin_country", "unknown")
    event_store.append(
        session_id=session_id,
        event_type=AuditEventType.WORKFLOW_FAILED,
        error=state.get("error_message"),
    )
    logger.error(f"Workflow failed: {state.get('error_message')}")
    return state


# ── Circuit breaker constants ─────────────────────────────────────────────
MAX_GRAPH_STEPS = 35          # hard cap on total node transitions (recursion_limit=50)
MAX_AGENT_RETRIES = 3         # max times any single agent can be invoked
MAX_TEST_RETRIES = 2          # max rule_tester failures before auto-completing


def _increment_graph_step(state: WizardAgentState) -> int:
    """Increment and return the global graph step counter."""
    step = state.get("graph_step", 0) + 1
    state["graph_step"] = step
    return step


def _increment_agent_retry(state: WizardAgentState, agent_name: str) -> int:
    """Increment and return the per-agent retry counter."""
    counts = state.get("agent_retry_counts", {})
    counts[agent_name] = counts.get(agent_name, 0) + 1
    state["agent_retry_counts"] = counts
    return counts[agent_name]


def route_from_supervisor(state: WizardAgentState) -> str:
    """Route based on supervisor decision with hard circuit breakers."""
    phase = state.get("current_phase", "fail")

    # ── Breaker 1: hard graph step limit ──
    step = _increment_graph_step(state)
    if step >= MAX_GRAPH_STEPS and phase not in ("complete", "fail"):
        logger.warning(f"Circuit breaker: graph_step={step} >= {MAX_GRAPH_STEPS}, forcing fail")
        state["error_message"] = f"Workflow exceeded {MAX_GRAPH_STEPS} graph steps"
        return "fail"

    # ── Breaker 2: iteration limit ──
    iteration = state.get("iteration", 0)
    max_iterations = state.get("max_iterations", 10)
    if iteration >= max_iterations and phase not in ("complete", "fail"):
        logger.warning(f"Circuit breaker: iteration={iteration} >= max={max_iterations}")
        return "fail"

    # ── Breaker 3: validation retry exhaustion ──
    retry_count = state.get("validation_retry_count", 0)
    if retry_count >= 3 and phase not in ("complete", "fail", "rule_tester"):
        return "validator"

    # ── Breaker 4: per-agent retry limit ──
    valid_routes = {
        "rule_analyzer", "data_dictionary", "cypher_generator",
        "validator", "reference_data", "rule_tester", "human_review", "complete", "fail"
    }

    if phase in valid_routes and phase not in ("complete", "fail", "human_review"):
        agent_counts = state.get("agent_retry_counts", {})
        agent_count = agent_counts.get(phase, 0)
        if agent_count >= MAX_AGENT_RETRIES:
            logger.warning(f"Circuit breaker: agent '{phase}' invoked {agent_count} times, skipping")
            skip_map = {
                "rule_analyzer": "cypher_generator",
                "data_dictionary": "cypher_generator",
                "cypher_generator": "validator",
                "validator": "rule_tester",
                "reference_data": "rule_tester",
                "rule_tester": "complete",
            }
            return skip_map.get(phase, "complete")

    if phase in valid_routes:
        return phase
    return "fail"


def entry_point_router(state: WizardAgentState) -> Union[str, List[str]]:
    """Determine initial nodes. If in agentic mode, run analyzer and dictionary in parallel."""
    if state.get("agentic_mode"):
        return ["rule_analyzer", "data_dictionary"]
    return "supervisor"


def build_rule_ingestion_graph(with_interrupt: bool = True) -> tuple:
    """Build optimized LangGraph workflow."""
    workflow = StateGraph(WizardAgentState)

    # Add nodes
    workflow.add_node("supervisor", supervisor_node)
    workflow.add_node("rule_analyzer", rule_analyzer_node)
    workflow.add_node("data_dictionary", data_dictionary_node)
    workflow.add_node("cypher_generator", cypher_generator_node)
    workflow.add_node("validator", validator_node)
    workflow.add_node("reference_data", reference_data_node)
    workflow.add_node("rule_tester", rule_tester_node)
    workflow.add_node("human_review", human_review_node)
    workflow.add_node("review_proposal", review_proposal_node)
    workflow.add_node("complete", complete_node)
    workflow.add_node("fail", fail_node)

    # ── Optimization: Entry Point Branching ──
    workflow.set_conditional_entry_point(
        entry_point_router,
        {
            "rule_analyzer": "rule_analyzer",
            "data_dictionary": "data_dictionary",
            "supervisor": "supervisor"
        }
    )

    # ── Routing Logic ──

    def _route_after_initial_agents(state: WizardAgentState) -> str:
        """After initial parallel nodes, join and move to cypher if both done."""
        # If in agentic mode and haven't run cypher yet, move to cypher
        if state.get("agentic_mode") and not state.get("cypher_queries") and state.get("iteration", 0) == 0:
            if state.get("rule_definition") and state.get("dictionary_result"):
                return "cypher_generator"
            return "supervisor"  # Fallback to supervisor to sync
        return "supervisor"

    def _route_after_cypher(state: WizardAgentState) -> str:
        """Fast path: go straight to validator after cypher in round 0."""
        if state.get("agentic_mode") and state.get("iteration", 0) == 0:
            return "validator"
        return "supervisor"

    def _route_after_validator(state: WizardAgentState) -> str:
        """Fast path: go straight to review if valid in round 0."""
        if state.get("agentic_mode") and state.get("iteration", 0) == 0:
            v_res = state.get("validation_result") or {}
            if v_res.get("overall_valid"):
                return "review_proposal"
        
        phase = state.get("current_phase", "supervisor")
        if phase == "rule_tester": return "rule_tester"
        if phase in ("complete", "review_proposal"): return "review_proposal"
        if phase == "fail": return "fail"
        return "supervisor"

    # Parallel agent transitions
    workflow.add_conditional_edges("rule_analyzer", _route_after_initial_agents, {"cypher_generator": "cypher_generator", "supervisor": "supervisor"})
    workflow.add_conditional_edges("data_dictionary", _route_after_initial_agents, {"cypher_generator": "cypher_generator", "supervisor": "supervisor"})
    
    workflow.add_conditional_edges("cypher_generator", _route_after_cypher, {"validator": "validator", "supervisor": "supervisor"})
    
    workflow.add_conditional_edges(
        "validator",
        _route_after_validator,
        {
            "rule_tester": "rule_tester",
            "review_proposal": "review_proposal",
            "fail": "fail",
            "supervisor": "supervisor",
        }
    )

    # Standard supervisor routing
    workflow.add_conditional_edges(
        "supervisor",
        route_from_supervisor,
        {
            "rule_analyzer": "rule_analyzer",
            "data_dictionary": "data_dictionary",
            "cypher_generator": "cypher_generator",
            "validator": "validator",
            "reference_data": "reference_data",
            "rule_tester": "rule_tester",
            "human_review": "human_review",
            "complete": "review_proposal",
            "fail": "fail",
        }
    )

    # Terminal nodes and other edges
    workflow.add_edge("rule_tester", "supervisor")
    workflow.add_edge("reference_data", "supervisor")
    workflow.add_edge("human_review", "supervisor")
    workflow.add_edge("review_proposal", "complete")
    workflow.add_edge("complete", END)
    workflow.add_edge("fail", END)

    checkpointer = MemorySaver()
    interrupt = ["human_review"] if with_interrupt else None

    compiled = workflow.compile(
        checkpointer=checkpointer,
        interrupt_before=interrupt,
    )

    return compiled, checkpointer


class RuleIngestionResult:
    """Result of running the rule ingestion workflow."""
    def __init__(self, state: WizardAgentState):
        self.success = state.get("success", False)
        self.rule_definition = state.get("rule_definition")
        self.cypher_queries = state.get("cypher_queries")
        self.dictionary_result = state.get("dictionary_result")
        self.analysis_result = state.get("analysis_result")
        self.validation_result = state.get("validation_result")
        self.test_results = state.get("test_results")
        self.proposal = state.get("proposal")
        self.error_message = state.get("error_message")
        self.iterations = state.get("iteration", 0)
        self.events = state.get("events", [])
        self.requires_human_input = state.get("requires_human_input", False)


def run_rule_ingestion(
    origin_country: str,
    scenario_type: str,
    receiving_countries: List[str],
    rule_text: str,
    data_categories: Optional[List[str]] = None,
    is_pii_related: bool = False,
    max_iterations: int = 10,
    thread_id: Optional[str] = None,
    agentic_mode: bool = False,
) -> RuleIngestionResult:
    """Run the rule ingestion workflow."""
    initial_state = create_initial_state(
        origin_country=origin_country,
        scenario_type=scenario_type,
        receiving_countries=receiving_countries,
        rule_text=rule_text,
        data_categories=data_categories,
        is_pii_related=is_pii_related,
        max_iterations=max_iterations,
        agentic_mode=agentic_mode,
    )

    event_store = get_event_store()
    event_store.append(
        session_id=origin_country,
        event_type=AuditEventType.WORKFLOW_STARTED,
        data={"rule_text": rule_text[:200], "agentic_mode": agentic_mode},
    )

    config = {"configurable": {"thread_id": thread_id or "default"}, "recursion_limit": 50}

    try:
        graph, _ = build_rule_ingestion_graph(with_interrupt=not agentic_mode)
        final_state = graph.invoke(initial_state, config)
        return RuleIngestionResult(final_state)
    except Exception as e:
        logger.error(f"Workflow execution failed: {e}", exc_info=True)
        error_state = initial_state.copy()
        error_state["success"] = False
        error_state["error_message"] = f"Workflow error: {str(e)}"
        return RuleIngestionResult(error_state)
